import { existsSync, readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const read = (path: string) => existsSync(path) ? readFileSync(path, 'utf8') : ''

describe('LHR shared design shells', () => {
  it('uses one centered authentication shell for every account entry page', () => {
    const authShell = read('components/auth-page-shell.tsx')

    expect(authShell).toContain('grid-cols-[1fr_auto_1fr]')
    expect(authShell).toContain('<BrandLogo priority')
    expect(authShell).toContain("max-w-md")

    for (const page of [
      'app/login/page.tsx',
      'app/register/page.tsx',
      'app/forgot-password/page.tsx',
      'app/reset-password/page.tsx',
      'app/verify-email/page.tsx',
      'app/verify-email-pending/page.tsx'
    ]) {
      expect(read(page), page).toContain('<AuthPageShell')
    }
  })

  it('keeps public presentation pages in the visitor shell instead of the member sidebar', () => {
    const shell = read('components/site-shell.tsx')

    expect(shell).toContain('publicPresentationRoutes')
    expect(shell).toContain("'/rencontres'")
    expect(shell).toContain("'/premium'")
    expect(shell).toContain("'/community-safety'")
    expect(shell).toContain('<VisitorLandingHeader')
  })

  it('gives every admin page a bounded modern shared surface', () => {
    const mainLayout = read('components/layout/main-layout.tsx')
    const adminHeader = read('components/admin-header.tsx')
    const styles = read('app/globals.css')

    expect(mainLayout).toContain('admin-shell')
    expect(adminHeader).toContain('<BrandLogo compact')
    expect(styles).toContain('.admin-shell .container')
    expect(styles).toContain('max-width: 1680px')
  })

  it('publishes professional site metadata and a clean legal footer', () => {
    const layout = read('app/layout.tsx')
    const footer = read('components/footer.tsx')

    expect(layout).toContain("title: 'Love Hotel Rencontre'")
    expect(layout).toContain("metadataBase: new URL('https://rencontrelovehotel.com')")
    expect(layout).not.toContain('Generated by create next app')
    expect(footer).toContain("href='/privacy'")
    expect(footer).not.toContain('DeploymentStamp')
  })
})

describe('LHR moderation presentation', () => {
  it('shows calendar-day message activity in the moderation cockpit', () => {
    const action = read('actions/admin-moderation-actions.ts')
    const page = read('app/admin/moderation/page.tsx')

    expect(action).toContain('messagesToday')
    expect(action).toContain("created_at >= CURRENT_DATE")
    expect(page).toContain("title='Messages aujourd’hui'")
    expect(page).toContain('counts?.messagesToday')
  })

  it('keeps targeted moderation prominent without reopening all private messages', () => {
    const page = read('app/admin/moderation/page.tsx')

    expect(page).toContain('Dossiers ciblés à examiner')
    expect(page).toContain("href='/moderation'")
    expect(page).not.toContain("href='/admin/messages'")
    expect(page).not.toContain('scanRecentMessagesForModeration')
  })
})
