import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('my profile matching UI', () => {
  it('turns /profile into a modern matching control center', () => {
    const page = readFileSync('app/profile/page.tsx', 'utf8')
    const editor = readFileSync('components/UserProfileEditor.tsx', 'utf8')
    const photos = readFileSync('components/UserPhotosManager.tsx', 'utf8')
    const preferences = readFileSync('components/PreferencesEditor.tsx', 'utf8')

    expect(page).toContain('Profil matching')
    expect(page).toContain('Score profil')
    expect(page).toContain('Ce qui aide à matcher')
    expect(page).toContain('Love Rooms')
    expect(page).toContain('Événements')
    expect(page).toContain('LhrV2Shell')
    expect(editor).toContain('Statut relationnel')
    expect(editor).toContain('Homme seul')
    expect(editor).toContain('Femme seule')
    expect(editor).toContain('Couple')
    expect(editor).toContain("formData.append('purpose', 'avatar')")
    expect(editor).toContain("fetch('/api/photos/upload'")
    expect(editor).toContain('Photo enregistrée')
    expect(editor).toContain('validateImageUploadFile')
    expect(editor).toContain('Formats acceptés : JPG, PNG ou WebP. Taille maximale : 8 Mo par photo.')
    expect(editor).toContain("role='alert'")
    expect(editor).toContain('Ajouter d&apos;autres photos')
    expect(editor).toContain("href='/profile?tab=photos'")
    expect(editor).not.toContain("getElementById('profile-photos-tab')")
    expect(page).toContain("requestedTab === 'photos' ? 'photos' : 'profile'")
    expect(page).toContain("key={requestedTab === 'photos' ? 'photos' : 'profile'}")
    expect(page).not.toContain('onUploadImage={uploadProfileImage}')
    expect(photos).toContain("const [uploading, setUploading]")
    expect(photos).toContain("role='alert'")
    expect(photos).toContain('Ajouter une photo')
    expect(photos).toContain('Photo sauvegardée')
    expect(photos).toContain('validateImageUploadFile')
    expect(photos).toContain('Formats acceptés : JPG, PNG ou WebP. Taille maximale : 8 Mo par photo.')
    expect(preferences).toContain('Intentions de rencontre')
    expect(preferences).toContain('Apéro jacuzzi')
    expect(preferences).toContain('Rideaux ouverts')
  })
})
