BEGIN;

ALTER TABLE conciergerie_requests
  ADD COLUMN IF NOT EXISTS venue_preference VARCHAR(160),
  ADD COLUMN IF NOT EXISTS desired_date VARCHAR(160),
  ADD COLUMN IF NOT EXISTS party_size VARCHAR(160),
  ADD COLUMN IF NOT EXISTS mood VARCHAR(120);

COMMIT;
