import type React from 'react'
import type { Metadata, Viewport } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from '@/components/providers'
import PwaUpdateNotification from '@/components/PwaUpdateNotification'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  metadataBase: new URL('http://localhost:3000'), // Ajoutez votre URL de production ici à terme
  title: 'Rencontres',
  description: 'Generated by create next app'
}

export const viewport: Viewport = {
  themeColor: 'black' // Ou la couleur que vous aviez définie
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='fr' suppressHydrationWarning>
      <body
        className={`${inter.className} bg-gradient-to-br from-[#1a0d2e] to-[#3d1155]`}
        suppressHydrationWarning
      >
        <Providers>
          {children}
          <PwaUpdateNotification />
        </Providers>
      </body>
    </html>
  )
}
